-- Supabase の SQL Editor で実行する council_chunks テーブル定義。
-- 既存テーブルがある場合も壊さず拡張できるよう、create/alter を併用している。

create extension if not exists vector;

create table if not exists council_chunks (
  id bigint generated by default as identity primary key,
  municipality text not null,
  slug text,
  meeting_name text not null,
  council_id bigint,
  schedule_id bigint,
  minute_id bigint,
  speaker text,
  speaker_name text,
  speaker_role text,
  agenda_title text,
  content text not null,
  embedding vector(768) not null
);

alter table council_chunks add column if not exists slug text;
alter table council_chunks add column if not exists council_id bigint;
alter table council_chunks add column if not exists schedule_id bigint;
alter table council_chunks add column if not exists minute_id bigint;
alter table council_chunks add column if not exists speaker_name text;
alter table council_chunks add column if not exists speaker_role text;
alter table council_chunks add column if not exists agenda_title text;

create index if not exists council_chunks_municipality_idx
  on council_chunks (municipality);

create index if not exists council_chunks_slug_idx
  on council_chunks (slug);

create index if not exists council_chunks_meeting_idx
  on council_chunks (meeting_name);

create index if not exists council_chunks_embedding_hnsw
  on council_chunks using hnsw (embedding vector_cosine_ops);
